services:
  moviepilot:
    image: ${DOCKER_MIRROR}docker.io/jxxghp/moviepilot-v2:${VERSION}
    container_name: moviepilot
    ports:
      - "${TRIM_SERVICE_PORT}:3000"
    volumes:
      - ${TRIM_PKGVAR}/config:/config
      - ${TRIM_PKGVAR}/core:/moviepilot
      - ${MEDIA_DIR:-${TRIM_PKGVAR}/media}:/media
      - ${DOWNLOAD_DIR:-${TRIM_PKGVAR}/downloads}:/downloads
    environment:
      - TZ=Asia/Shanghai
      - PUID=${TRIM_UID}
      - PGID=${TRIM_GID}
      - UMASK=022
      - PORT=3000
      - GITHUB_PROXY=https://gh-proxy.com/
      - SUPERUSER_PASSWORD=${SUPERUSER_PASSWORD:-password}
    restart: unless-stopped
