services:
  kodbox:
    image: kodcloud/kodbox:${VERSION}
    container_name: kodbox
    ports:
      - "${TRIM_SERVICE_PORT}:80"
    volumes:
      - ${TRIM_PKGVAR}/data:/var/www/html
    environment:
      - TZ=Asia/Shanghai
    restart: unless-stopped
