services:
  vaultwarden:
    image: ${DOCKER_MIRROR-docker.conversun.com/docker.io/}vaultwarden/server:${VERSION}
    container_name: vaultwarden
    ports:
      - "${TRIM_SERVICE_PORT}:80"
    volumes:
      - ${TRIM_PKGVAR}/data:/data
    environment:
      - TZ=Asia/Shanghai
    restart: unless-stopped
